### ISSUE TITLE
gl_info import error

### ISSUE THREAD

**Issue by jorgehatccrma** [qbilius/psychopy_ext#6]
I'm trying to run the demo. If I type `python run.py`, I get small window with an error saying "cannot import name gl_info". If I open the python interpreter and type `from pyglet.gl import gl_info`, it works okay (I can use its methods and modules). I guess this rules out a problem with the pyglet installation.

To add more info, when I type `python run.py` I see the "cannot import name gl_info" error window and I can't even see the experiments. I see an empty window, without any buttons or input boxes or anything. I do see the menu with the other experiments, but if I click any of them I get the "cannot import name gl_info" and don't see any controls.

If, on the other hand, I go into the ipython intepreter and import `gl_info` (eg `from pyglet.gl import gl_info`), then I can run the demo (`%run run.py`) and get to see the controls for every experiment (I don't see the initial error window described at the beginning). BUT, as soon as I try to run any experiment (i.e. click the run button), in the console I get the "ImportError: cannot import name gl_info". The full trace is

    initializing...Traceback (most recent call last):
      File "run.py", line 27, in <module>
        ui.Control(exp_choices, title='Demo Project', size=(560,550))
      File "/usr/local/lib/python2.7/site-packages/psychopy_ext/ui.py", line 73, in __init__
        self.cmd(exp_choices)
      File "/usr/local/lib/python2.7/site-packages/psychopy_ext/ui.py", line 145, in cmd
        __import__(module)
      File "/Users/jorgeh/Documents/CCRMA/research/beatTapExperiment/demos/scripts/trivial.py", line 9, in <module>
        from psychopy_ext import exp
      File "/usr/local/lib/python2.7/site-packages/psychopy_ext/exp.py", line 31, in <module>
        import psychopy.info
      File "/usr/local/lib/python2.7/site-packages/psychopy/info.py", line 13, in <module>
        from pyglet.gl import *
      File "/usr/local/lib/python2.7/site-packages/pyglet/gl/__init__.py", line 101, in <module>
        from pyglet.gl import gl_info
    ImportError: cannot import name gl_info

Any advice/ideas?

**Comment by BeibinLi** [comment]
Hi All, I had the same issue.

My psychoPy runs fine last week, but I encountered this problem today. I also tried to uninstall & install psychopy and Python27 today. So, I have a clean installation of Python and PsychoPy now. 

I am using Windows 7, Python 2.7.10, and PsychoPy 1.83.01 (I also tried 1.82.01).

I have errors when calling
 " import psychopy.info" or "wizard.BenchamarkWizard()"

By calling wizard.BenchmarkWizard()

I had the following issue
Traceback (most recent call last):
  File "C:\Users\aaa\Desktop\Psychopy_ET\xxx.py", line 10, in <module>
    from psychopy import wizard
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy-1.83.01-py2.7.egg\psychopy\wizard.py", line 12, in <module>
    from pyglet.gl import gl_info
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\pyglet\gl\__init__.py", line 235, in <module>
    import pyglet.window
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\pyglet\window\__init__.py", line 1811, in <module>
    gl._create_shadow_window()
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\pyglet\gl\__init__.py", line 205, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\pyglet\window\win32\__init__.py", line 131, in __init__
    super(Win32Window, self).__init__(*args, **kwargs)
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\pyglet\window\__init__.py", line 559, in __init__
    self._create()
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\pyglet\window\win32\__init__.py", line 266, in _create
    self.switch_to()
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\pyglet\window\win32\__init__.py", line 305, in switch_to
    self.context.set_current()
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\pyglet\gl\win32.py", line 212, in set_current
    wgl.wglMakeCurrent(self.canvas.hdc, self._context)
WindowsError: exception: access violation reading 0x00000018

**Comment by qbilius** [comment]
Again, this looks like psychopy issue to me; I'm not seeing any relation to psychopy_ext here – or am I missing something here?

**Comment by qbilius** [comment]
In other words, can you even run PsychoPy demos? Seems like something is up with your pyglet / opengl, but I don't know enough about these libraries to hekp you. Also, I just did a fresh install of PsychoPy 1.82.01 on my Ubuntu machine and import psychopy.info works just fine.

**Comment by BeibinLi** [comment]
Thank you for the reply! Yes, I guess it's a psychopy issue.

**Comment by qbilius** [comment]
Issue moved to https://github.com/psychopy/psychopy/issues/1065
